# Generated by Django 2.2.12 on 2020-05-18 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hide_from_toc', models.BooleanField(default=False)),
                ('visible_to_staff_only', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSectionSequence',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hide_from_toc', models.BooleanField(default=False)),
                ('visible_to_staff_only', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('published_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSequence',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='learning_sequences.LearningContext')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningcontext',
            index=models.Index(fields=['-published_at'], name='learning_se_publish_62319b_idx'),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_sequences', to='learning_sequences.LearningContext'),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_sequences.CourseSection'),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_sequences.LearningSequence'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning_sequences.LearningContext'),
        ),
        migrations.AlterUniqueTogether(
            name='learningsequence',
            unique_together={('learning_context', 'usage_key')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesectionsequence',
            unique_together={('learning_context', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('learning_context', 'usage_key')},
        ),
        migrations.AlterIndexTogether(
            name='coursesection',
            index_together={('learning_context', 'order')},
        ),
    ]
